### ISSUE TITLE
Add composer.lock to gitignore

### ISSUE THREAD

**Issue by larizzatg** [joestrong/retroachievements-composer#21]
Composer.lock is being tracked by git, this file is generated when composer is installed/updated and should be in the project and not tracket by git. 

Add a line in .gitignore file to remove the composer.lock from git track

**Comment by mannion007** [comment]
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by larizzatg** [comment]
Thanks @mannion007  I have a wrong assumption about it.

**Comment by mannion007** [comment]
@skayablars hey, no problem at all!
