### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by joestrong** [joestrong/retroachievements-composer#7]
Important contents for the CONTRIBUTING.md:
 - Creating a new branch off of the develop branch
 - All changes to the code should have appropriate unit tests
 - All code should match PSR-2 style
 - Submit a pull request againt develop as the base branch
 - All travis checks will need to pass

**Comment by Supun94** [comment]
@joestrong Need to add CONTRIBUTING.md file relevant to the project? I'm just confused about the issue description. I would like to work this issue. Shall I update CONTRIBUTING.md ?

**Comment by joestrong** [comment]
@Supun94 I will need a CONTRIBUTING.md file in the root, perhaps following a similar format to what other projects use.

The issue description wasn't clear, I've updated it. The bullet points are for the contents of the CONTRIBUTING.md file (but it can be reworded to whatever fits the typical CONTRIBUTING.md style)

**Comment by Supun94** [comment]
@joestrong Thanks for the update. Please review the PR #8

**Comment by joestrong** [comment]
Added in 52dc451a2978e8011512f9be861b0bcfa8f7e03c
